apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-data-transfer
spec:
  activeDeadlineSeconds: 1728000         # The job will be terminated after 20 days.
  ttlSecondsAfterFinished: 60          # Job will be deleted after 60 seconds
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: shared-memory          # This is to resolve the dataloader OOM issue.
          emptyDir:
            medium: Memory
        - name: dataset-volume
          persistentVolumeClaim:
            claimName: mnist-pvc # <------- your PVC name
      containers:
        - name: data-transfer-pvc
          image: ubuntu:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
          resources:
            limits:
              memory: 8Gi
              cpu: 2
            requests:
              memory: 8Gi
              cpu: 2
          volumeMounts:
            - name: dataset-volume
              mountPath: /data        # You PVC is mounted as /data attached to the transfer POD
            - name: shared-memory
              mountPath: /dev/shm